apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devkit-ns
  name: orders-deployment
  labels:
    app: devkit
    name: orders-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-pod
  template:
    metadata:
      name: orders-pod
      labels:
        app: devkit
        name: orders-pod

    spec:
      containers:
        - name: orders
          image: devkit.azurecr.io/logistics-orders:#{Build.BuildId}#
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: envvar-configmap
            - secretRef:
                name: api-secrets
            - secretRef:
                name: orders-secrets
          volumeMounts:
            - mountPath: app/infrastructure
              name: base-settings
            - mountPath: app/configs
              name: orders-settings
      volumes:
        - name: orders-settings
          configMap:
            name: orders-settings-configmap
        - name: base-settings
          configMap:
            name: base-settings-configmap

---
apiVersion: v1
kind: Service
metadata:
  namespace: devkit-ns
  name: orders-cluterip
  labels:
    app: devkit
    name: orders-cluterip

spec:
  type: ClusterIP
  selector:
    app: devkit
    name: orders-pod
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-settings-configmap
data:
  appsettings.json: |-
    {
      "AllowedHosts": "*",
      "APIDefinition": {
          "Name": "Logistics Orders API",
          "Description": "Order API tracks orders and deliveries.",
          "Version": "v1"
      },
      "ConsulConfiguration": {
        "ConsulHost": "http://consul-clusterip:8500",
          "ServiceName": "orders-api",
          "DataCenter": "dc1",
          "ServiceId": "logistics.orders",
          "Port": "80",
          "Tags": [
            "logistics", 
            "orders", 
            "internal"],
          "Meta": {
          "version": "1.0.0",
          "sdk": "logistics",
          "type": "domain",
          "domain": "orders"
          }
      },
      "SearchWorkOptions": {
          "MaxPageSize": 10,
          "MaxSearchDistanceInKm": 5
      },
      "DeliveryOptions": {
          "BaseCost": 70.0,
          "BaseDistanceInKm": 3.0,
          "CostPerKm": 7.0,
          "SystemFeePercentage": 20.0,
          "Tax": 0.0
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  namespace: devkit-ns
  name: orders-secrets
  labels:
    app: devkit
    name: orders-secrets

data:
  RepositoryOptions__DatabaseName: b3JkZXJz
  RepositoryOptions__ConnectionString: bW9uZ29kYitzcnY6Ly9zbmFwcHktdGVzdDpQYXNzdzByZDEyMyUyNC10ZXN0QHNuYXBweWNsdXN0ZXIuY2dkcjIubW9uZ29kYi5uZXQvb3JkZXJzP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
