apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devkit-ns
  name: consul-deployment
  labels:
    app: devkit
    name: consul-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: devkit
      name: consul-pod
  template:
    metadata:
      namespace: devkit-ns
      name: consul-pod
      labels:
        app: devkit
        name: consul-pod

    spec:
      containers:
        - name: consul
          image: consul:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
          ports:
            - containerPort: 8500

---
apiVersion: v1
kind: Service
metadata:
  namespace: devkit-ns
  name: consul-clusterip
  labels:
    app: devkit
    name: consul-clusterip

spec:
  type: ClusterIP
  selector:
    app: devkit
    name: consul-pod
  ports:
    - port: 8500
      targetPort: 8500
